### ISSUE TITLE
Invalid URLs for splits downloading

### ISSUE THREAD

**Issue by Hryts** [MichiganCOG/devil#4]
Hello!
I was trying to setup your benchmark and ran into a problem with executing
` python -m src.main.download_devil_splits fvi-fgd-h -e` command.
I found out that is was caused by invalid links provided in `SPLIT_TO_REMOTE_URL_MAP` variable in **src/main/download_devil_splits.py** file. (The links are not found).
I would be grateful if you were to solve the issue.

**Comment by UrskaJ** [comment]
Any plans to fix this data issue? The links are not working...

**Comment by rszeto-sy** [comment]
Hi everyone,

Apologizes for the late response (and thank you Urska for emailing me directly. @Hryts's issue was likely due to the redirection not working; that has since been fixed. @UrskaJ, you're seeing a similar issue because the machine hosting the data is currently down. I'm working on getting it back up; I appreciate your patience and attention.
