### ISSUE TITLE
Question on  the Dataset Generation Pipeline

### ISSUE THREAD

**Issue by AMontiB** [MichiganCOG/devil#5]
Hi, first of all, thank you for your work. I had time to read the paper just once but I think it is a significant contribution to the literature.
I would like to ask if you could provide additional details on the generation pipeline you adopt to inpaint your videos (i.e. you extract the video frames from the original video, inpaint these frames and then encode the frames back to video?).  Moreover, all the experiments were performed on the inpainted videos, the inpainted frames before video encoding or the frames that you extracted from the inpainted videos?

**Comment by rszeto-sy** [comment]
Hello Andrea,

Thanks for your interest, and sincerest apologies for the late reply. Inpainting/evaluation is performed on image frames extracted from the video via FFmpeg; there is no re-encoding back into a video format except for visualization purposes. In other words, we assume that the image frames extracted via FFmpeg contain the true color values, and that there is no loss of information from inpainting or evaluating after re-encoding (since we do not perform any re-encoding). Hope this answers your questions.

**Comment by AMontiB** [comment]
Hello, thank you for your answer! It was all I needed. Congratulations again for the great work!
